### PR TITLE
fix(dns-resolution-grapher.js): fix tooltip positioning

### PR DESCRIPTION
**Pull request by vinaypillai**
Take mouse position into account when positioning tooltip in order to avoid placing it offscreen

### CODE REVIEW

**Comment by lanrat** [comment]
I just tested this pr, is this still the expected behavior?

Screen Shot 2020-06-30 at 8 48 07 AM

**Comment by vinaypillai** [comment]
That's a bit strange, but I think so. It anchors to either the left or right size of the tooltip depending on where the mouse is on hover (mouse is on the left, anchors to the left/ mouse is on the right, anchors to the right). I could try dividing the screen into thirds and adding a center anchor?

**Comment by lanrat** [comment]
Could the entire tooltip be moved so that it is allowed to go outside of the graph box if necessary?

**Comment by vinaypillai** [comment]
Sure, but it might trigger some horizontal scrolling

**Comment by lanrat** [comment]
Is it possible to have the tooltip not be part of the graph box and its own element to prevent that from happening?
there should be no need for any scrolling.

**Comment by vinaypillai** [comment]
The window itself would have horizontal scrolling since now that the tooltip isn't cut off by the edges of the graph, it extends wider than the screen.

**Comment by vinaypillai** [comment]
I could cap the width of tooltip without cutting off text but at that point it would probably be easier just to cap it at the width of the container and adjust the positioning based off of that.

**Comment by lanrat** [comment]
In the above screenshot, whats preventing the tooltip from extending to the right where there is just white space?

**Comment by vinaypillai** [comment]
Because there isnt enough whitespace for the tooltip to extend without triggering horizontal scrolling

**Comment by vinaypillai** [comment]
image

image

**Comment by vinaypillai** [comment]
Alright this should eliminate any cutoff or overflow issues

**Comment by lanrat** [comment]
LGTM 👍

**Pull request merged**
